### ISSUE TITLE
Keras framework

### ISSUE THREAD

**Issue by brianprichardson** [suragnair/alpha-zero-general#11]
Apologize for formatting.
Cannot run Keras framework from scratch.  Made 2 minor changes to main.py as follows:
from Coach import Coach
from othello.OthelloGame import OthelloGame
from othello.keras.NNet import NNetWrapper as nn  <----------------keras instead of pytorch
from utils import *

args = dotdict({
    'numIters': 1000,
    'numEps': 100,
    'tempThreshold': 15,
    'updateThreshold': 0.6,
    'maxlenOfQueue': 200000,
    'numMCTSSims': 25,
    'arenaCompare': 40,
    'cpuct': 1,
    'checkpoint': './tempkeras/', <---------------just to keep frameworks separate
    'load_model': False,
    'load_folder_file': ('/dev/models/8x100x50','best.pth.tar'),
})

if __name__=="__main__":
    g = OthelloGame(6)
    nnet = nn(g)
    if args.load_model:
        nnet.load_checkpoint(args.load_folder_file[0], args.load_folder_file[1])
    c = Coach(g, nnet, args)
    c.learn()

And get this:
`(alpha-zero-general) brian@Tinker2Ubuntu:~/alpha-zero-general/bin/alpha-zero-general$ python mainkeras.py
Using TensorFlow backend.
/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
------ITER 1------
2018-01-05 15:26:14.110757: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2
2018-01-05 15:26:14.230623: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-01-05 15:26:14.231014: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.7845
pciBusID: 0000:03:00.0
totalMemory: 7.92GiB freeMemory: 3.83GiB
2018-01-05 15:26:14.231031: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000:03:00.0, compute capability: 6.1)
Self Play |####                            | (15/100) Eps Time: 6.800s | Total: Self Play |#####                           | (16/100) Eps Time: 6.570s | Total: Self Play |#####                           | (17/100) Eps Time: 6.379s | Total: Self Play |#####                           | (18/100) Eps Time: 6.219s | Total: Self Play |######                          | (19/100) Eps Time: 6.070s | Total: 0:01:55 | ETA:Self Play |################################| (100/100) Eps Time: 3.966s | Total: 0:06:36 | ETA: 0:00:04
Checkpoint Directory does not exist! Making directory ./tempkeras/
Traceback (most recent call last):
  File "mainkeras.py", line 29, in <module>
    c.learn()
  File "/home/brian/alpha-zero-general/bin/alpha-zero-general/Coach.py", line 91, in learn
    pnet.load_checkpoint(folder=self.args.checkpoint, filename='temp.pth.tar')
  File "/home/brian/alpha-zero-general/bin/alpha-zero-general/othello/keras/NNet.py", line 70, in load_checkpoint
    raise("No model in path {}".format(filepath))
TypeError: exceptions must derive from BaseException
(alpha-zero-general) brian@Tinker2Ubuntu:~/alpha-zero-general/bin/alpha-zero-general$ 
`

**Comment by suragnair** [comment]
Yes, as mentioned in README: 

> Choose your framework in `main.py.`

**Comment by brianprichardson** [comment]
from othello.keras.NNet import NNetWrapper as nn <----------------keras instead of pytorch

Is this not choosing the framework in main.py per the readme, or am I missing something ?
Thanks,
Brian
