### ISSUE TITLE
Is best_act = -1 normal ?

### ISSUE THREAD

**Issue by 23201199** [suragnair/alpha-zero-general#36]
I got this error :

Traceback (most recent call last):
    File "/usr/lib/python2.7/dist-packages/pudb/__init__.py", line 77, in runscript
        dbg._runscript(mainpyfile)
    File "/usr/lib/python2.7/dist-packages/pudb/debugger.py", line 419, in _runscript 
       self.run(statement, globals=globals_, locals=locals_)
    File "/usr/lib/python2.7/bdb.py", line 400, in run
       exec cmd in globals, locals
     File "<string>", line 1, in <module>
     File "main.py", line 29, in <module>  
        c.learn()                         
     File "Coach.py", line 99, in learn                               
       pwins, nwins, draws = arena.playGames(self.args.arenaCompare)   
     File "Arena.py", line 81, in playGames                                                                  
       gameResult = self.playGame(verbose=verbose)                                          
     File "Arena.py", line 46, in playGame                 
       action = players[curPlayer+1](self.game.getCanonicalForm(board, curPlayer))            
     File "Coach.py", line 98, in <lambda>                                                                  
       lambda x: np.argmax(nmcts.getActionProb(x, temp=0)), self.game)                           
     File "MCTS.py", line 31, in getActionProb             
       self.search(canonicalBoard)                                                                      
     File "MCTS.py", line 106, in search                                                                        
       v = self.search(next_s)                                                      
     File "MCTS.py", line 106, in search                                                            
       v = self.search(next_s)                                                                                
     File "MCTS.py", line 106, in search                                                                      
       v = self.search(next_s)
    File "MCTS.py", line 106, in search 
       v = self.search(next_s)                                                                                    
     File "MCTS.py", line 106, in search                                                                        
       v = self.search(next_s)                                                                                  
     File "MCTS.py", line 103, in search                                                                     
       next_s, next_player = self.game.getNextState(canonicalBoard, 1, a)                              
     File "othello/OthelloGame.py", line 34, in getNextState                                                         
       b.execute_move(move, player)                                                                                
     File "othello/OthelloLogic.py", line 111, in execute_move                                                     
       assert len(list(flips))>0                                                                                   
   AssertionError         

When i execute exectue_move() function my action and move is -1 and (-1 ,5)

**Comment by suragnair** [comment]
Nope. It is related to #27 and #23 . We are still looking for a fix.
